#!/usr/bin/env bash
# tools/waybeam-overlay-gen.sh
#
# Regenerates .github/waybeam-overlay/{files,patches}/ from the live tree so
# the overlay (consumed by CI) never drifts from the customization living at
# the live paths. Reads the manicfest at .github/waybeam-overlay/MANIFEST.txt.
#
# This is the pre-commit source-of-truth engine: edit the live file at
# general/package/rtl88x2cu/rtl88x2cu.mk, run this (or just commit —
# the .githooks/pre-commit hook runs it for you), and the overlay copy is
# refreshed in the same commit. The CI overlay is therefore always a faithful
# projection of the live customization.
#
# Default upstream: OpenIPC/firmware master. Override with git config:
#   git config waybeam.upstreamURL https://github.com/OpenIPC/firmware.git
#   git config waybeam.upstreamRef  master
# Exit codes: 0 regenerated (or already-current), 1 manifest/IO error,
#             2 live-tree missing a file the manifest references.
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

UP_URL="${WAYBEAM_UPSTREAM_URL:-$(git config waybeam.upstreamURL 2>/dev/null || echo https://github.com/OpenIPC/firmware.git)}"
UP_REF="${WAYBEAM_UPSTREAM_REF:-$(git config waybeam.upstreamRef 2>/dev/null || echo master)}"

OVERLAY=".github/waybeam-overlay"
MANIFEST="$OVERLAY/MANIFEST.txt"
FILES="$OVERLAY/files"
PATCHES="$OVERLAY/patches"

[ -f "$MANIFEST" ] || { echo "::error::missing $MANIFEST" >&2; exit 1; }

# Lazily provision an `upstream` remote for first-run in fresh clones.
if ! git remote get-url upstream >/dev/null 2>&1; then
  echo "waybeam: adding upstream remote $UP_URL"
  git remote add upstream "$UP_URL"
fi
echo "waybeam: fetching upstream $UP_REF (depth 1)..."
git fetch --quiet --depth=1 upstream "$UP_REF"
UP_SHA="$(git rev-parse "upstream/$UP_REF")"
echo "waybeam: upstream $UP_REF @ ${UP_SHA:0:7}"

# --- clean destinations so deletions in the live tree propagate -----------
rm -rf "$FILES" "$PATCHES"
mkdir -p "$FILES" "$PATCHES"

# --- process the manifest -------------------------------------------------
name_from_path() { printf '%s' "$1" | sed -e 's|/|_|g' -e 's|^general_||' -e 's|^br-ext-chip-sigmastar_configs_||'; }

while IFS= read -r line || [ -n "$line" ]; do
  line="${line%$'\r'}"             # tolerate CRLF checkouts (Windows clones)
  line="${line%%#*}"                # strip comments
  case "$line" in
    ''|\ *) ;;
  esac
  verb="${line%% *}"
  path="${line#* }"
  path="${path## }"; path="${path%% }"
  [ -z "$verb" ] || [ -z "$path" ] && continue
  case "$verb" in
    add)
      [ -f "$path" ] || { echo "::error::manifest `add` references missing live file: $path" >&2; exit 2; }
      dst="$FILES/$path"
      mkdir -p "$(dirname "$dst")"
      cp -f "$path" "$dst"
      echo "waybeam: add  $path"
      ;;
    patch)
      [ -f "$path" ] || { echo "::error::manifest `patch` references missing live file: $path" >&2; exit 2; }
      out="$PATCHES/$(name_from_path "$path").patch"
      if git diff --quiet "upstream/$UP_REF" -- "$path"; then
        echo "waybeam: $path unchanged vs upstream — no patch produced"
      else
        git diff --no-color "upstream/$UP_REF" -- "$path" > "$out"
        echo "waybeam: patch $path -> $(basename "$out") ($(wc -l < "$out")L)"
      fi
      ;;
    *)
      echo "::error::unknown manifest verb '$verb' for: $path" >&2; exit 1
      ;;
  esac
done < "$MANIFEST"

# --- stamp provenance so a reviewer can match the overlay to the live tree -
{
  echo "# auto-generated by tools/waybeam-overlay-gen.sh — do not hand-edit."
  echo "# upstream=$UP_REF sha=$UP_SHA"
  echo "# generated=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
} > "$OVERLAY/PROVENANCE.txt"

echo "waybeam: overlay regenerated against upstream ${UP_SHA:0:7}"
